directories:
  output: release
  buildResources: resources
productName: Ticket Form
appId: org.develar.ticketformtool
files:
  - filter:
      - dist/
      - node_modules/
      - app.html
      - main.prod.js
      - main.prod.js.map
      - package.json
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
linux:
  target:
    - AppImage
    - deb
  category: Development
electronVersion: 7.1.13
